name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install huggingface_hub
        run: pip install huggingface_hub

      - name: Upload to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.SAFESHOT }}
        run: |
          python -c "
import os
from huggingface_hub import HfApi
api = HfApi()
api.upload_folder(
    repo_id='Swagata-Roy/SafeShot',
    folder_path='.',
    repo_type='space',
    token=os.environ['SAFESHOT'],
    delete_patterns=['*']
)
"
